# permissions for end users to edit kafkaconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: external-connect-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkaconnector-editor-role
rules:
- apiGroups:
  - external.saiello.github.io
  resources:
  - kafkaconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external.saiello.github.io
  resources:
  - kafkaconnectors/status
  verbs:
  - get
