---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create test kind cluster
      command: kind create cluster --name osdk-test --kubeconfig {{ kubeconfig }}

    - name: Create Kafka Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ strimzi_namespace }}'

    - import_tasks: ../default/kustomize-strimzi.yml
      vars:
        state: present