---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create Kafka Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ strimzi_namespace }}'

    - import_tasks: kustomize-strimzi.yml
      vars:
        state: present
